Better help, prevent output to stdout with compressed data

diff --git a/knb b/knb
--- a/knb
+++ b/knb
@@ -28,7 +28,7 @@ function cleanandexit {
 	# Cleaning temp directory
 	if [ "$CLEANDIR" = "true" ] 
 	then
-		[ -d $DATADIR ] && touch $DATADIR/something && rm $DATADIR/* && rmdir $DATADIR
+		[ ! -z "$DATADIR" ] && [ -d $DATADIR ] && touch $DATADIR/something && rm $DATADIR/* && rmdir $DATADIR
 	else
 		info "Keeping data directory, you will have to clean it manually."
 		info "$DATADIR"
@@ -58,7 +58,7 @@ function waitpod {
 # Default config
 #==============================================================================
 
-VERSION=1.1.1
+VERSION=1.2.0
 GENERATOR="github.com/InfraBuilder/k8s-bench-suite"
 BENCHMARK_DATE=$(date -u "+%Y-%m-%d %H:%M:%S")
 DEBUG=false
@@ -72,7 +72,9 @@ BENCHMARK_DURATION="10"
 SOCKET_BUFFER_SIZE="256K"
 RESSOURCE_TO_CLEAN_BEFORE_EXIT=""
 OUTPUT_FORMAT="text"
+FILENAME="/dev/stdout"
 CLEANDIR="true"
+FROM_DATA="false"
 
 export LC_ALL=C # Trick to no depend on locale
 BIN_AWK="awk"
@@ -84,37 +86,69 @@ BIN_AWK="awk"
 function usage {
 	cat <<-EOF
 
-	$0 is a network benchmark tool for Kubernetes CNI
+	knb is a network benchmark tool for Kubernetes CNI
+
+	There are two modes : 
+	- benchmark mode : will actually run benchmark on a cluster
+	- from data mode : read data generated by previous benchmark with "-o data" flag
 	
-	Mandatory flags :
+	=====[ Benchmark mode ]====================================================
+
+	 Mandatory flags :
 	    -cn <nodename>
 	    --client-node <nodename>    : Define kubernetes node name that will host the client part
 	    -sn <nodename>
 	    --server-node <nodename>    : Define kubernetes node name that will host the server part
 	
-	Optionnal flags :
-	    --debug                     : Set the debug level to "debug"
-	    --debug-level <level>       : Set the debug level (values: standard, warn, info, debug) 
+	 Optionnal flags :
 	    -d <time-in-scd>
 	    --duration <time-in-scd>    : Set the benchmark duration for each test in seconds. (Default ${BENCHMARK_DURATION})
-	    -h
-	    --help                      : Display this help message
 	    -k
 	    --keep                      : Keep data directory instead of cleaning it (contains raw benchmark data)
 	    -n <namespace>
 	    --namespace <namespace>     : Set the target kubernetes namespace
-	    -o <format>
-	    --output <format>           : Set the output format (values: text, yaml, json)
 	    -sbs <size>
 	    --socket-buffer-size <size> : Set the socket buffer size (Default: $SOCKET_BUFFER_SIZE)
 	    -t <time-in-scd>
 	    --timeout <time-in-scd>     : Set the pod ready wait timeout in seconds. (Default ${POD_WAIT_TIMEOUT})
+
+	=====[ From Data mode =====================================================
+
+	Mandatory flags :
+	    -fd <path>
+	    --from-data <path>          : Define the path to the data to read from
+
+	=====[ Common optionnal flags ]============================================
+
+	    --debug                     : Set the debug level to "debug"
+	    --debug-level <level>       : Set the debug level (values: standard, warn, info, debug) 
+	    -h
+	    --help                      : Display this help message
+	    -f <filepath>
+	    --file <filepath>           : Set the output file
+	    -o <format>
+	    --output <format>           : Set the output format (values: text, yaml, json, data)
 	    -v
 	    --verbose                   : Activate the verbose mode by setting debug-level to 'info'
 	    -V
 	    --version                   : Show current script version
 
-	Example : $0 -v -cn node1 -sn node2
+	=====[ Examples ]==========================================================
+	
+	  Simple benchmark from "node1" to "node2" in verbose mode
+	  -------------------------------------------------------------------------
+	  | knb -v -cn node1 -sn node2                                            |
+	  -------------------------------------------------------------------------
+
+	  Benchmark from "nA" to "nB" with data saved in file "mybench.knbdata"
+	  -------------------------------------------------------------------------
+	  | knb -cn nA -sn nB -o data -f mybench.knbdata                          |
+	  -------------------------------------------------------------------------
+
+	  Generate report in json from previous benchmark file "mybench.knbdata"
+	  -------------------------------------------------------------------------
+	  | knb -fd mybench.knbdata -o json                                       |
+	  -------------------------------------------------------------------------
 
 EOF
 }
@@ -198,6 +232,11 @@ function run-client {
 			print "cpu-user cpu-nice cpu-system cpu-iowait cpu-steal memory-used records-number"; 
 			printf "%.2f %.2f %.2f %.2f %.2f %d %d\n",U/NR,N/NR,S/NR,I/NR,T/NR,M/NR,NR
 		}' > $DATADIR/$POD_NAME-client.avg
+}
+
+function compute-data-result {
+
+	(cd $DATADIR; tar -czf - .)
 }
 
 function compute-json-result {
@@ -358,6 +397,33 @@ function compute-text-result {
 	echo "========================================================="
 }
 
+function generate-report {
+	case $OUTPUT_FORMAT in
+		json) compute-json-result > $FILENAME;;
+		yaml) compute-yaml-result > $FILENAME;;
+		data) compute-data-result > $FILENAME;;
+		*)    compute-text-result > $FILENAME;;
+	esac
+}
+
+function source-data-from-dir {
+	source "$DATADIR/env"
+	$DEBUG && debug "GENERATOR=$GENERATOR"
+	$DEBUG && debug "VERSION=$VERSION"
+	$DEBUG && debug "BENCHMARK_DATE=$BENCHMARK_DATE"
+	$DEBUG && debug "SERVER_NODE=$SERVER_NODE"
+	$DEBUG && debug "CLIENT_NODE=$CLIENT_NODE"
+
+	$DEBUG && debug "MONITOR_SERVER_POD_NAME=$MONITOR_SERVER_POD_NAME"
+	$DEBUG && debug "MONITOR_CLIENT_POD_NAME=$MONITOR_CLIENT_POD_NAME"
+	$DEBUG && debug "SERVER_POD_NAME=$SERVER_POD_NAME"
+	$DEBUG && debug "IDLE_POD_NAME=$IDLE_POD_NAME"
+	$DEBUG && debug "CLIENT_TCP_P2P_POD_NAME=$CLIENT_TCP_P2P_POD_NAME"
+	$DEBUG && debug "CLIENT_UDP_P2P_POD_NAME=$CLIENT_UDP_P2P_POD_NAME"
+	$DEBUG && debug "CLIENT_TCP_P2S_POD_NAME=$CLIENT_TCP_P2S_POD_NAME"
+	$DEBUG && debug "CLIENT_UDP_P2S_POD_NAME=$CLIENT_UDP_P2S_POD_NAME"
+}
+
 #==============================================================================
 # Argument parsing
 #==============================================================================
@@ -389,6 +455,13 @@ do
 			POD_WAIT_TIMEOUT="$1"
 			info "Setting timeout to ${1}s"
 			;;
+		--from-data|-fd)
+			shift
+			FROM_DATA="true"
+			CLEANDIR="false"
+			DATADIR="$1"
+			info "Benchmark will not run, report will be generated from ${1}"
+			;;
 		--socket-buffer-size|-sbs)
 			shift
 			SOCKET_BUFFER_SIZE="$1"
@@ -399,6 +472,12 @@ do
 			BENCHMARK_DURATION="$1"
 			info "Setting benchmark duration to ${1}s"
 			;;
+		--file|-f)
+			shift
+			FILENAME="$1"
+			[ "$FILENAME" = "-" ] && FILENAME="/dev/stdout"
+			info "Output file set to ${FILENAME}"
+			;;
 		--output|-o)
 			shift
 			
@@ -407,7 +486,8 @@ do
 				json) ;;
 				yaml) ;;
 				text) ;;
-				*) fatal "Unknown output format '$1'. Here is a list of acceptable formats : text, json, yaml";;
+				data) ;;
+				*) fatal "Unknown output format '$1'. Here is a list of acceptable formats : text, json, yaml, data";;
 			esac
 			
 			info "Setting output format to ${1}s"
@@ -454,6 +534,49 @@ $DEBUG && debug "Argument parsing done"
 # Preflight checks
 #==============================================================================
 
+[ "$FILENAME" = "/dev/stdout" -a "$OUTPUT_FORMAT" = "data" ] && fatal "I cowardly refuse to output data on stdout, please use '-f' flag"
+
+# We do not run benchmark test, we source from existing data
+if $FROM_DATA
+then
+	$DEBUG && debug "Entering from data report generation"
+
+	# Data source is a directory, let's source data
+	if [ -d "$DATADIR" -a -f "$DATADIR/env" ]
+	then
+		$DEBUG && debug "Data is a directory, sourcing env file"
+
+		source-data-from-dir
+		generate-report
+
+	# In this case, the datasource is a file, a compressed tar
+	elif [ -f "$DATADIR" ]
+	then
+		$DEBUG && debug "Data is a file"
+
+		# Saving filename
+		FROM_DATA_FILE="$DATADIR"
+		
+		# Generating a temp dir to work
+		DATADIR="$(mktemp -d)"
+
+		# Setting the cleandir flag, as datadit is now a temp dir
+		CLEANDIR="true"
+		
+		# Extracting data in DATADIR tmp dir
+		tar -xzf "$FROM_DATA_FILE" -C "$DATADIR" || fatal "Cannot extract data from file $FROM_DATA_FILE"
+
+		source-data-from-dir
+		generate-report
+
+	else
+		fatal "Cannot recognize data format $DATADIR"
+	fi
+
+	# In every case, we didn't want to run benchmark test so we exit
+	cleanandexit
+fi
+
 [ "$SERVER_NODE" = "" -o "$CLIENT_NODE" = "" ] \
 	&& fatal "Both client node and server node must be set (--server-node and --client-node)"
 
@@ -492,20 +615,20 @@ $DEBUG && debug "Client UDP P2S pod name will be $CLIENT_UDP_P2S_POD_NAME"
 
 # Creating env file with metadata
 cat <<EOF > $DATADIR/env
-GENERATOR=$GENERATOR
-VERSION=$VERSION
-BENCHMARK_DATE=$BENCHMARK_DATE
-SERVER_NODE=$SERVER_NODE
-CLIENT_NODE=$CLIENT_NODE
+GENERATOR="$GENERATOR"
+VERSION="$VERSION"
+BENCHMARK_DATE="$BENCHMARK_DATE"
+SERVER_NODE="$SERVER_NODE"
+CLIENT_NODE="$CLIENT_NODE"
 
-MONITOR_SERVER_POD_NAME=$MONITOR_SERVER_POD_NAME
-MONITOR_CLIENT_POD_NAME=$MONITOR_CLIENT_POD_NAME
-SERVER_POD_NAME=$SERVER_POD_NAME
-IDLE_POD_NAME=$IDLE_POD_NAME
-CLIENT_TCP_P2P_POD_NAME=$CLIENT_TCP_P2P_POD_NAME
-CLIENT_UDP_P2P_POD_NAME=$CLIENT_UDP_P2P_POD_NAME
-CLIENT_TCP_P2S_POD_NAME=$CLIENT_TCP_P2S_POD_NAME
-CLIENT_UDP_P2S_POD_NAME=$CLIENT_UDP_P2S_POD_NAME
+MONITOR_SERVER_POD_NAME="$MONITOR_SERVER_POD_NAME"
+MONITOR_CLIENT_POD_NAME="$MONITOR_CLIENT_POD_NAME"
+SERVER_POD_NAME="$SERVER_POD_NAME"
+IDLE_POD_NAME="$IDLE_POD_NAME"
+CLIENT_TCP_P2P_POD_NAME="$CLIENT_TCP_P2P_POD_NAME"
+CLIENT_UDP_P2P_POD_NAME="$CLIENT_UDP_P2P_POD_NAME"
+CLIENT_TCP_P2S_POD_NAME="$CLIENT_TCP_P2S_POD_NAME"
+CLIENT_UDP_P2S_POD_NAME="$CLIENT_UDP_P2S_POD_NAME"
 EOF
 
 # Catching CTRL-C
@@ -646,11 +769,7 @@ run-client $CLIENT_UDP_P2S_POD_NAME $SERVER_SERVICE_NAME udp
 # Output
 #==============================================================================
 
-case $OUTPUT_FORMAT in
-	json) compute-json-result ;;
-	yaml) compute-yaml-result ;;
-	*)    compute-text-result ;;
-esac
+generate-report
 
 #==============================================================================
 # Cleaning
